bionic_contactus:
    pattern:  /contactus
    defaults: { _controller: BionicUniversityContactBundle:Default:index }
    requirements:
        _method:  GET|POST
        
bionic_contactsent:
    pattern:  /contactsent
    defaults: { _controller: BionicUniversityContactBundle:Default:sent }

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /contactus
        permanent: true