parameters:
#    bionic_university_contact.example.class: BionicUniversity\ContactBundle\Example

services:
#    bionic_university_contact.example:
#        class: %bionic_university_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
